---
title: "hw_3"
output:獨立演唱會畫圖
---

爬Json檔並簡單整理dataframe
```{r}
install.packages("ggmap")
install.packages("plyr")
library(httr)
library(jsonlite)
library(ggplot2)
library(ggmap)
library(plyr) 
library(stringr)
options(stringsAsFactors = F)

url <- "https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=5"
df <- fromJSON(content(GET(url), "text"))
info <- df$showInfo
new.df <- data.frame(matrix(unlist(info), byrow=T, ncol= 8))
new.df <- new.df[ ,-1] 
new.df <- new.df[ ,-7]
new.df <- cbind(df$title, new.df)
View(new.df)
names(new.df) <- c("Band",
                   "Location",
                   "Place",
                   "OnSale",
                   "Price",
                   "Lat",
                   "Lng")
new.df$Lat<-as.numeric(new.df$Lat) 
new.df$Lng<-as.numeric(new.df$Lng) 

```


在Google上顯示演唱會的地點
```{r}
map.df <- new.df[complete.cases(new.df[ , 6:7]), ]
map.df <- map.df[ , -(2:5)]
ggmap(get_googlemap(center = c(120.493515, 23.670),
                    zoom = 8,
                    maptype = 'roadmap')) +
  geom_point(data = map.df,
             aes(x = Lng, y = Lat),
             colour = "red",
             size = 3.5 ,
             alpha = 0.3 )
```


演唱會在哪裡辦？
```{r}
place.df <- data.frame(count(new.df, "Place"))
ggplot(data=place.df, aes(x=Place, y=freq , fill=Place) ,family = "NotoSansCJKtc-Light") +
  geom_bar(stat="identity")
```


哪些縣市最常辦演唱會？
-從loacation欄取出縣市名
-畫長條圖
```{r}
county.df <- c()
for( i in new.df$Location[1:104] ){
   print(i)
   county <-substr( i , 1, 3)
   county.df <- rbind(county.df, county)
}

county.df <- as.data.frame(county.df)
```


這些獨立樂團演唱會的價格多少？
-整理new.df裡的"Price"欄
-全部取單人價格
-畫可愛的bar圖
```{r}

```

待解決：
1. Mac電腦上的plot如何顯示中文店家名？
2. 調整縣市欄位的資料，
   ex：台北市／臺北市統一改成Taipei
       803/高雄市統一改成Kaohsiung
3. 用正規表達式將"Price"欄位整理成只有單人價格
4. Rmd目前無法knit出html

